"""add description by cabinet

Revision ID: e039ddac8f54
Revises: 6758f28685dd
Create Date: 2025-10-19 20:23:32.699952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e039ddac8f54'
down_revision: Union[str, Sequence[str], None] = '6758f28685dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinets', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cabinets', 'description')
    # ### end Alembic commands ###
